InventoryManagement/Areas/Admin/Controllers/BrandController.cs
using InventoryManagement.DataAccess.Repository.IRepository;
using InventoryManagement.Models;
using InventoryManagement.Utilities;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BrandController : Controller
    {
        private readonly IUnitofWork _unitofWork;

        public BrandController(IUnitofWork unitofWork)
        {
            _unitofWork = unitofWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Brand brand = new Brand();
            if (id == null)
            {
                // A category need to be created
                brand.Status = true;
                return View(brand);
            }
            brand = await _unitofWork.Brand.Get(id.GetValueOrDefault());
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Brand brand)
        {
            if (ModelState.IsValid)
            {
                if(brand.Id == 0)
                {
                    await _unitofWork.Brand.Add(brand);
                    TempData[StaticDefinitions.Success] = "Marca creada exitosamente.";
                }else
                {
                    _unitofWork.Brand.Update(brand);
                    TempData[StaticDefinitions.Success] = "Marca actulizada exitosamente.";
                }

                await _unitofWork.Save();
                return RedirectToAction(nameof(Index));
            }
            TempData[StaticDefinitions.Error] = "Error al guardar marca.";
            return View(brand);
        }

        #region API
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var all = await _unitofWork.Brand.GetAll();

            return Json(new {data = all});
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var brand = await _unitofWork.Brand.Get(id);
            if (brand == null)
            {
                return Json(new { success = false, message = "Marca no encontrada." });
            }
            _unitofWork.Brand.Remove(brand);
            await _unitofWork.Save();

            return Json(new { success = true, message = "Marca borrada exitosamente." });
        }

        [ActionName("ValidateName")]
        public async Task<IActionResult> ValidateName(string name, int id = 0)
{
            bool value = false;
            var list = await _unitofWork.Brand.GetAll();
            if (id == 0)
            {
                value = list.Any(b => b.Name.ToLower().Trim() == name.ToLower().Trim());
            }
            else
            {
                value = list.Any(b => b.Name.ToLower().Trim() == name.ToLower().Trim() && b.Id != id);
            }

            if (value)
            {
                return Json(new { data = true });
            }
            return Json(new { data = false });
        }
        #endregion
    }
}

InventoryManagement/Areas/Admin/Controllers/CategoryController.cs
using InventoryManagement.DataAccess.Repository.IRepository;
using InventoryManagement.Models;
using InventoryManagement.Utilities;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitofWork _unitofWork;

        public CategoryController(IUnitofWork unitofWork)
        {
            _unitofWork = unitofWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Category category = new Category();
            if (id == null)
            {
                // A category need to be created
                category.Status = true;
                return View(category);
            }
            category = await _unitofWork.Category.Get(id.GetValueOrDefault());
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Category category)
        {
            if (ModelState.IsValid)
            {
                if(category.Id == 0)
                {
                    await _unitofWork.Category.Add(category);
                    TempData[StaticDefinitions.Success] = "Categoría creada exitosamente.";
                }else
                {
                    _unitofWork.Category.Update(category);
                    TempData[StaticDefinitions.Success] = "Categoría actulizada exitosamente.";
                }

                await _unitofWork.Save();
                return RedirectToAction(nameof(Index));
            }
            TempData[StaticDefinitions.Error] = "Error al guardar categoría.";
            return View(category);
        }

        #region API
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var all = await _unitofWork.Category.GetAll();

            return Json(new {data = all});
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var category = await _unitofWork.Category.Get(id);
            if (category == null)
            {
                return Json(new { success = false, message = "Categoría no encontrada." });
            }
            _unitofWork.Category.Remove(category);
            await _unitofWork.Save();

            return Json(new { success = true, message = "Categoría borrada exitosamente." });
        }

        [ActionName("ValidateName")]
        public async Task<IActionResult> ValidateName(string name, int id = 0)
{
            bool value = false;
            var list = await _unitofWork.Category.GetAll();
            if (id == 0)
            {
                value = list.Any(b => b.Name.ToLower().Trim() == name.ToLower().Trim());
            }
            else
            {
                value = list.Any(b => b.Name.ToLower().Trim() == name.ToLower().Trim() && b.Id != id);
            }

            if (value)
            {
                return Json(new { data = true });
            }
            return Json(new { data = false });
        }
        #endregion
    }
}

InventoryManagement/Areas/Admin/Controllers/WarehouseController.cs
using InventoryManagement.DataAccess.Repository.IRepository;
using InventoryManagement.Models;
using InventoryManagement.Utilities;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class WarehouseController : Controller
    {
        private readonly IUnitofWork _unitofWork;

        public WarehouseController(IUnitofWork unitofWork)
        {
            _unitofWork = unitofWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Warehouse warehouse = new Warehouse();
            if (id == null)
            {
                // A warehouse need to be created
                warehouse.Status = true;
                return View(warehouse);
            }
            warehouse = await _unitofWork.Warehouse.Get(id.GetValueOrDefault());
            if (warehouse == null)
            {
                return NotFound();
            }
            return View(warehouse);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Warehouse warehouse)
        {
            if (ModelState.IsValid)
            {
                if(warehouse.Id == 0)
                {
                    await _unitofWork.Warehouse.Add(warehouse);
                    TempData[StaticDefinitions.Success] = "Bodega creada exitosamente.";
                }else
                {
                    _unitofWork.Warehouse.Update(warehouse);
                    TempData[StaticDefinitions.Success] = "Bodega actulizada exitosamente.";
                }

                await _unitofWork.Save();
                return RedirectToAction(nameof(Index));
            }
            TempData[StaticDefinitions.Error] = "Error al guardar bodega.";
            return View(warehouse);
        }

        #region API
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var all = await _unitofWork.Warehouse.GetAll();

            return Json(new {data = all});
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var warehouse = await _unitofWork.Warehouse.Get(id);
            if (warehouse == null)
            {
                return Json(new { success = false, message = "Bodega no encontrada." });
            }
            _unitofWork.Warehouse.Remove(warehouse);
            await _unitofWork.Save();

            return Json(new { success = true, message = "Bodega borrada exitosamente." });
        }

        [ActionName("ValidateName")]
        public async Task<IActionResult> ValidateName(string name, int id = 0)
{
            bool value = false;
            var list = await _unitofWork.Warehouse.GetAll();
            if (id == 0)
            {
                value = list.Any(b => b.Name.ToLower().Trim() == name.ToLower().Trim());
            }
            else
            {
                value = list.Any(b => b.Name.ToLower().Trim() == name.ToLower().Trim() && b.Id != id);
            }

            if (value)
            {
                return Json(new { data = true });
            }
            return Json(new { data = false });
        }
        #endregion
    }
}

InventoryManagement/Views/Shared/_CreateAndGoBackButton.cshtml
<div class="d-flex gap-5">
    <button type="submit" class="btn btn-primary" onfocus="false"><i class="bi bi-plus-square-fill"></i> Crear</button>
    <a asp-action="Index" class="btn btn-success"><i class="bi bi-arrow-return-left"></i> Regresar</a>
</div>

InventoryManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InventoryManagement</title>
    <script type="importmap"></script>

    <link rel="icon" type="image/png" href="~/img/almacen.png" asp-append-version="true" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InventoryManagement.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdn.datatables.net/2.3.2/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/hogar.png" width="50px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Contenido</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Warehouse" asp-action="Index">Bodegas</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Categorías</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Brand" asp-action="Index">Marcas</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Productos</a></li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - InventoryManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.datatables.net/2.3.2/js/dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/2.3.2/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

InventoryManagement/Views/Shared/_Notifications.cshtml
@using InventoryManagement.Utilities

@if(TempData[StaticDefinitions.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.success('@TempData[StaticDefinitions.Success]')
    </script>
}

@if(TempData[StaticDefinitions.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.error('@TempData[StaticDefinitions.Error]')
    </script>
}

InventoryManagement/Views/Shared/_UpdateAndGoBack.cshtml
@model int

<div class="d-flex gap-5">
    <button type="submit" class="btn btn-primary" onfocus="false" asp-route-id="@Model"><i class="bi bi-pencil-square"></i> Guardar cambios</button>
    <a asp-action="Index" class="btn btn-success"><i class="bi bi-arrow-return-left"></i> Regresar</a>
</div>